trigger:
- master
jobs:
  - job:
    displayName: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 1
      - script: cargo -v build --release
        displayName: Build
      - script: cargo -v clippy
        displayName: Clippy
      - publish: target/release/android-commander
        artifact: android-commander-linux
  - job:
    displayName: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self
        fetchDepth: 1
      - script: cargo -v build --release
        displayName: Build
      - script: cargo -v clippy
        displayName: Clippy
      - publish: target/release/android-commander.exe
        artifact: android-commander-win
  - job:
    displayName: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - checkout: self
        fetchDepth: 1
        displayName: Setup Rust
      - script: cargo -v build --release
        displayName: Build
      - script: cargo -v clippy
        displayName: Clippy
      - publish: target/release/android-commander
        artifact: android-commander-osx
  - job:
    displayName: macOS-M1
    pool:
      name: Default
      demands:
        - rust
        - agent.os -equals Darwin
    variables:
      RUSTUP_TOOLCHAIN: 1.48.0-x86_64
    steps:
      - script: |
          cargo -v build --release 2> >(tee stderr.log >&2)
          CODE=$?
          grep -qe ^warning stderr.log && grep -e ^warning stderr.log | xargs -ILINE echo "##vso[task.logissue type=warning]LINE" || true
          grep -qe ^error stderr.log && grep -e ^error stderr.log | xargs -ILINE echo "##vso[task.logissue type=error]LINE" || true
          exit $CODE
        displayName: Build
      - script: |
          cargo -v clippy 2> >(tee stderr.log >&2)
          CODE=$?
          grep -qe ^warning stderr.log && grep -e ^warning stderr.log | xargs -ILINE echo "##vso[task.logissue type=warning]LINE" || true
          grep -qe ^error stderr.log && grep -e ^error stderr.log | xargs -ILINE echo "##vso[task.logissue type=error]LINE" || true
          exit $CODE
        displayName: Clippy
      - publish: target/release/android-commander
        artifact: android-commander-osx
