/*
 * Copyright 2021 sukawasatoru
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package jp.tinyport.androidcommander.server

import android.view.KeyEvent

enum class KeyCode {
    KEYCODE_UNKNOWN,
    KEYCODE_SOFT_LEFT,
    KEYCODE_SOFT_RIGHT,
    KEYCODE_HOME,
    KEYCODE_BACK,
    KEYCODE_CALL,
    KEYCODE_ENDCALL,
    KEYCODE_0,
    KEYCODE_1,
    KEYCODE_2,
    KEYCODE_3,
    KEYCODE_4,
    KEYCODE_5,
    KEYCODE_6,
    KEYCODE_7,
    KEYCODE_8,
    KEYCODE_9,
    KEYCODE_STAR,
    KEYCODE_POUND,
    KEYCODE_DPAD_UP,
    KEYCODE_DPAD_DOWN,
    KEYCODE_DPAD_LEFT,
    KEYCODE_DPAD_RIGHT,
    KEYCODE_DPAD_CENTER,
    KEYCODE_VOLUME_UP,
    KEYCODE_VOLUME_DOWN,
    KEYCODE_POWER,
    KEYCODE_CAMERA,
    KEYCODE_CLEAR,
    KEYCODE_A,
    KEYCODE_B,
    KEYCODE_C,
    KEYCODE_D,
    KEYCODE_E,
    KEYCODE_F,
    KEYCODE_G,
    KEYCODE_H,
    KEYCODE_I,
    KEYCODE_J,
    KEYCODE_K,
    KEYCODE_L,
    KEYCODE_M,
    KEYCODE_N,
    KEYCODE_O,
    KEYCODE_P,
    KEYCODE_Q,
    KEYCODE_R,
    KEYCODE_S,
    KEYCODE_T,
    KEYCODE_U,
    KEYCODE_V,
    KEYCODE_W,
    KEYCODE_X,
    KEYCODE_Y,
    KEYCODE_Z,
    KEYCODE_COMMA,
    KEYCODE_PERIOD,
    KEYCODE_ALT_LEFT,
    KEYCODE_ALT_RIGHT,
    KEYCODE_SHIFT_LEFT,
    KEYCODE_SHIFT_RIGHT,
    KEYCODE_TAB,
    KEYCODE_SPACE,
    KEYCODE_SYM,
    KEYCODE_EXPLORER,
    KEYCODE_ENVELOPE,
    KEYCODE_ENTER,
    KEYCODE_DEL,
    KEYCODE_GRAVE,
    KEYCODE_MINUS,
    KEYCODE_EQUALS,
    KEYCODE_LEFT_BRACKET,
    KEYCODE_RIGHT_BRACKET,
    KEYCODE_BACKSLASH,
    KEYCODE_SEMICOLON,
    KEYCODE_APOSTROPHE,
    KEYCODE_SLASH,
    KEYCODE_AT,
    KEYCODE_NUM,
    KEYCODE_HEADSETHOOK,
    KEYCODE_FOCUS,
    KEYCODE_PLUS,
    KEYCODE_MENU,
    KEYCODE_NOTIFICATION,
    KEYCODE_SEARCH,
    KEYCODE_MEDIA_PLAY_PAUSE,
    KEYCODE_MEDIA_STOP,
    KEYCODE_MEDIA_NEXT,
    KEYCODE_MEDIA_PREVIOUS,
    KEYCODE_MEDIA_REWIND,
    KEYCODE_MEDIA_FAST_FORWARD,
    KEYCODE_MUTE,
    KEYCODE_PAGE_UP,
    KEYCODE_PAGE_DOWN,
    KEYCODE_PICTSYMBOLS,
    KEYCODE_SWITCH_CHARSET,
    KEYCODE_BUTTON_A,
    KEYCODE_BUTTON_B,
    KEYCODE_BUTTON_C,
    KEYCODE_BUTTON_X,
    KEYCODE_BUTTON_Y,
    KEYCODE_BUTTON_Z,
    KEYCODE_BUTTON_L1,
    KEYCODE_BUTTON_R1,
    KEYCODE_BUTTON_L2,
    KEYCODE_BUTTON_R2,
    KEYCODE_BUTTON_THUMBL,
    KEYCODE_BUTTON_THUMBR,
    KEYCODE_BUTTON_START,
    KEYCODE_BUTTON_SELECT,
    KEYCODE_BUTTON_MODE,
    KEYCODE_ESCAPE,
    KEYCODE_FORWARD_DEL,
    KEYCODE_CTRL_LEFT,
    KEYCODE_CTRL_RIGHT,
    KEYCODE_CAPS_LOCK,
    KEYCODE_SCROLL_LOCK,
    KEYCODE_META_LEFT,
    KEYCODE_META_RIGHT,
    KEYCODE_FUNCTION,
    KEYCODE_SYSRQ,
    KEYCODE_BREAK,
    KEYCODE_MOVE_HOME,
    KEYCODE_MOVE_END,
    KEYCODE_INSERT,
    KEYCODE_FORWARD,
    KEYCODE_MEDIA_PLAY,
    KEYCODE_MEDIA_PAUSE,
    KEYCODE_MEDIA_CLOSE,
    KEYCODE_MEDIA_EJECT,
    KEYCODE_MEDIA_RECORD,
    KEYCODE_F1,
    KEYCODE_F2,
    KEYCODE_F3,
    KEYCODE_F4,
    KEYCODE_F5,
    KEYCODE_F6,
    KEYCODE_F7,
    KEYCODE_F8,
    KEYCODE_F9,
    KEYCODE_F10,
    KEYCODE_F11,
    KEYCODE_F12,
    KEYCODE_NUM_LOCK,
    KEYCODE_NUMPAD_0,
    KEYCODE_NUMPAD_1,
    KEYCODE_NUMPAD_2,
    KEYCODE_NUMPAD_3,
    KEYCODE_NUMPAD_4,
    KEYCODE_NUMPAD_5,
    KEYCODE_NUMPAD_6,
    KEYCODE_NUMPAD_7,
    KEYCODE_NUMPAD_8,
    KEYCODE_NUMPAD_9,
    KEYCODE_NUMPAD_DIVIDE,
    KEYCODE_NUMPAD_MULTIPLY,
    KEYCODE_NUMPAD_SUBTRACT,
    KEYCODE_NUMPAD_ADD,
    KEYCODE_NUMPAD_DOT,
    KEYCODE_NUMPAD_COMMA,
    KEYCODE_NUMPAD_ENTER,
    KEYCODE_NUMPAD_EQUALS,
    KEYCODE_NUMPAD_LEFT_PAREN,
    KEYCODE_NUMPAD_RIGHT_PAREN,
    KEYCODE_VOLUME_MUTE,
    KEYCODE_INFO,
    KEYCODE_CHANNEL_UP,
    KEYCODE_CHANNEL_DOWN,
    KEYCODE_ZOOM_IN,
    KEYCODE_ZOOM_OUT,
    KEYCODE_TV,
    KEYCODE_WINDOW,
    KEYCODE_GUIDE,
    KEYCODE_DVR,
    KEYCODE_BOOKMARK,
    KEYCODE_CAPTIONS,
    KEYCODE_SETTINGS,
    KEYCODE_TV_POWER,
    KEYCODE_TV_INPUT,
    KEYCODE_STB_POWER,
    KEYCODE_STB_INPUT,
    KEYCODE_AVR_POWER,
    KEYCODE_AVR_INPUT,
    KEYCODE_PROG_RED,
    KEYCODE_PROG_GREEN,
    KEYCODE_PROG_YELLOW,
    KEYCODE_PROG_BLUE,
    KEYCODE_APP_SWITCH,
    KEYCODE_BUTTON_1,
    KEYCODE_BUTTON_2,
    KEYCODE_BUTTON_3,
    KEYCODE_BUTTON_4,
    KEYCODE_BUTTON_5,
    KEYCODE_BUTTON_6,
    KEYCODE_BUTTON_7,
    KEYCODE_BUTTON_8,
    KEYCODE_BUTTON_9,
    KEYCODE_BUTTON_10,
    KEYCODE_BUTTON_11,
    KEYCODE_BUTTON_12,
    KEYCODE_BUTTON_13,
    KEYCODE_BUTTON_14,
    KEYCODE_BUTTON_15,
    KEYCODE_BUTTON_16,
    KEYCODE_LANGUAGE_SWITCH,
    KEYCODE_MANNER_MODE,
    KEYCODE_3D_MODE,
    KEYCODE_CONTACTS,
    KEYCODE_CALENDAR,
    KEYCODE_MUSIC,
    KEYCODE_CALCULATOR,
    KEYCODE_ZENKAKU_HANKAKU,
    KEYCODE_EISU,
    KEYCODE_MUHENKAN,
    KEYCODE_HENKAN,
    KEYCODE_KATAKANA_HIRAGANA,
    KEYCODE_YEN,
    KEYCODE_RO,
    KEYCODE_KANA,
    KEYCODE_ASSIST,
    KEYCODE_BRIGHTNESS_DOWN,
    KEYCODE_BRIGHTNESS_UP,
    KEYCODE_MEDIA_AUDIO_TRACK,
    KEYCODE_SLEEP,
    KEYCODE_WAKEUP,
    KEYCODE_PAIRING,
    KEYCODE_MEDIA_TOP_MENU,
    KEYCODE_11,
    KEYCODE_12,
    KEYCODE_LAST_CHANNEL,
    KEYCODE_TV_DATA_SERVICE,
    KEYCODE_VOICE_ASSIST,
    KEYCODE_TV_RADIO_SERVICE,
    KEYCODE_TV_TELETEXT,
    KEYCODE_TV_NUMBER_ENTRY,
    KEYCODE_TV_TERRESTRIAL_ANALOG,
    KEYCODE_TV_TERRESTRIAL_DIGITAL,
    KEYCODE_TV_SATELLITE,
    KEYCODE_TV_SATELLITE_BS,
    KEYCODE_TV_SATELLITE_CS,
    KEYCODE_TV_SATELLITE_SERVICE,
    KEYCODE_TV_NETWORK,
    KEYCODE_TV_ANTENNA_CABLE,
    KEYCODE_TV_INPUT_HDMI_1,
    KEYCODE_TV_INPUT_HDMI_2,
    KEYCODE_TV_INPUT_HDMI_3,
    KEYCODE_TV_INPUT_HDMI_4,
    KEYCODE_TV_INPUT_COMPOSITE_1,
    KEYCODE_TV_INPUT_COMPOSITE_2,
    KEYCODE_TV_INPUT_COMPONENT_1,
    KEYCODE_TV_INPUT_COMPONENT_2,
    KEYCODE_TV_INPUT_VGA_1,
    KEYCODE_TV_AUDIO_DESCRIPTION,
    KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP,
    KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN,
    KEYCODE_TV_ZOOM_MODE,
    KEYCODE_TV_CONTENTS_MENU,
    KEYCODE_TV_MEDIA_CONTEXT_MENU,
    KEYCODE_TV_TIMER_PROGRAMMING,
    KEYCODE_HELP,
    KEYCODE_NAVIGATE_PREVIOUS,
    KEYCODE_NAVIGATE_NEXT,
    KEYCODE_NAVIGATE_IN,
    KEYCODE_NAVIGATE_OUT,
    KEYCODE_STEM_PRIMARY,
    KEYCODE_STEM_1,
    KEYCODE_STEM_2,
    KEYCODE_STEM_3,
    KEYCODE_DPAD_UP_LEFT,
    KEYCODE_DPAD_DOWN_LEFT,
    KEYCODE_DPAD_UP_RIGHT,
    KEYCODE_DPAD_DOWN_RIGHT,
    KEYCODE_MEDIA_SKIP_FORWARD,
    KEYCODE_MEDIA_SKIP_BACKWARD,
    KEYCODE_MEDIA_STEP_FORWARD,
    KEYCODE_MEDIA_STEP_BACKWARD,
    KEYCODE_SOFT_SLEEP,
    KEYCODE_CUT,
    KEYCODE_COPY,
    KEYCODE_PASTE,
    KEYCODE_SYSTEM_NAVIGATION_UP,
    KEYCODE_SYSTEM_NAVIGATION_DOWN,
    KEYCODE_SYSTEM_NAVIGATION_LEFT,
    KEYCODE_SYSTEM_NAVIGATION_RIGHT,
    KEYCODE_ALL_APPS,
    KEYCODE_REFRESH,
    KEYCODE_THUMBS_UP,
    KEYCODE_THUMBS_DOWN,
    KEYCODE_PROFILE_SWITCH;

    companion object {
        fun from(value: String): KeyCode? {
            return values().find { it.name == value }
        }
    }

    val code: Int
        get() = when (this) {
            KEYCODE_UNKNOWN -> KeyEvent.KEYCODE_UNKNOWN
            KEYCODE_SOFT_LEFT -> KeyEvent.KEYCODE_SOFT_LEFT
            KEYCODE_SOFT_RIGHT -> KeyEvent.KEYCODE_SOFT_RIGHT
            KEYCODE_HOME -> KeyEvent.KEYCODE_HOME
            KEYCODE_BACK -> KeyEvent.KEYCODE_BACK
            KEYCODE_CALL -> KeyEvent.KEYCODE_CALL
            KEYCODE_ENDCALL -> KeyEvent.KEYCODE_ENDCALL
            KEYCODE_0 -> KeyEvent.KEYCODE_0
            KEYCODE_1 -> KeyEvent.KEYCODE_1
            KEYCODE_2 -> KeyEvent.KEYCODE_2
            KEYCODE_3 -> KeyEvent.KEYCODE_3
            KEYCODE_4 -> KeyEvent.KEYCODE_4
            KEYCODE_5 -> KeyEvent.KEYCODE_5
            KEYCODE_6 -> KeyEvent.KEYCODE_6
            KEYCODE_7 -> KeyEvent.KEYCODE_7
            KEYCODE_8 -> KeyEvent.KEYCODE_8
            KEYCODE_9 -> KeyEvent.KEYCODE_9
            KEYCODE_STAR -> KeyEvent.KEYCODE_STAR
            KEYCODE_POUND -> KeyEvent.KEYCODE_POUND
            KEYCODE_DPAD_UP -> KeyEvent.KEYCODE_DPAD_UP
            KEYCODE_DPAD_DOWN -> KeyEvent.KEYCODE_DPAD_DOWN
            KEYCODE_DPAD_LEFT -> KeyEvent.KEYCODE_DPAD_LEFT
            KEYCODE_DPAD_RIGHT -> KeyEvent.KEYCODE_DPAD_RIGHT
            KEYCODE_DPAD_CENTER -> KeyEvent.KEYCODE_DPAD_CENTER
            KEYCODE_VOLUME_UP -> KeyEvent.KEYCODE_VOLUME_UP
            KEYCODE_VOLUME_DOWN -> KeyEvent.KEYCODE_VOLUME_DOWN
            KEYCODE_POWER -> KeyEvent.KEYCODE_POWER
            KEYCODE_CAMERA -> KeyEvent.KEYCODE_CAMERA
            KEYCODE_CLEAR -> KeyEvent.KEYCODE_CLEAR
            KEYCODE_A -> KeyEvent.KEYCODE_A
            KEYCODE_B -> KeyEvent.KEYCODE_B
            KEYCODE_C -> KeyEvent.KEYCODE_C
            KEYCODE_D -> KeyEvent.KEYCODE_D
            KEYCODE_E -> KeyEvent.KEYCODE_E
            KEYCODE_F -> KeyEvent.KEYCODE_F
            KEYCODE_G -> KeyEvent.KEYCODE_G
            KEYCODE_H -> KeyEvent.KEYCODE_H
            KEYCODE_I -> KeyEvent.KEYCODE_I
            KEYCODE_J -> KeyEvent.KEYCODE_J
            KEYCODE_K -> KeyEvent.KEYCODE_K
            KEYCODE_L -> KeyEvent.KEYCODE_L
            KEYCODE_M -> KeyEvent.KEYCODE_M
            KEYCODE_N -> KeyEvent.KEYCODE_N
            KEYCODE_O -> KeyEvent.KEYCODE_O
            KEYCODE_P -> KeyEvent.KEYCODE_P
            KEYCODE_Q -> KeyEvent.KEYCODE_Q
            KEYCODE_R -> KeyEvent.KEYCODE_R
            KEYCODE_S -> KeyEvent.KEYCODE_S
            KEYCODE_T -> KeyEvent.KEYCODE_T
            KEYCODE_U -> KeyEvent.KEYCODE_U
            KEYCODE_V -> KeyEvent.KEYCODE_V
            KEYCODE_W -> KeyEvent.KEYCODE_W
            KEYCODE_X -> KeyEvent.KEYCODE_X
            KEYCODE_Y -> KeyEvent.KEYCODE_Y
            KEYCODE_Z -> KeyEvent.KEYCODE_Z
            KEYCODE_COMMA -> KeyEvent.KEYCODE_COMMA
            KEYCODE_PERIOD -> KeyEvent.KEYCODE_PERIOD
            KEYCODE_ALT_LEFT -> KeyEvent.KEYCODE_ALT_LEFT
            KEYCODE_ALT_RIGHT -> KeyEvent.KEYCODE_ALT_RIGHT
            KEYCODE_SHIFT_LEFT -> KeyEvent.KEYCODE_SHIFT_LEFT
            KEYCODE_SHIFT_RIGHT -> KeyEvent.KEYCODE_SHIFT_RIGHT
            KEYCODE_TAB -> KeyEvent.KEYCODE_TAB
            KEYCODE_SPACE -> KeyEvent.KEYCODE_SPACE
            KEYCODE_SYM -> KeyEvent.KEYCODE_SYM
            KEYCODE_EXPLORER -> KeyEvent.KEYCODE_EXPLORER
            KEYCODE_ENVELOPE -> KeyEvent.KEYCODE_ENVELOPE
            KEYCODE_ENTER -> KeyEvent.KEYCODE_ENTER
            KEYCODE_DEL -> KeyEvent.KEYCODE_DEL
            KEYCODE_GRAVE -> KeyEvent.KEYCODE_GRAVE
            KEYCODE_MINUS -> KeyEvent.KEYCODE_MINUS
            KEYCODE_EQUALS -> KeyEvent.KEYCODE_EQUALS
            KEYCODE_LEFT_BRACKET -> KeyEvent.KEYCODE_LEFT_BRACKET
            KEYCODE_RIGHT_BRACKET -> KeyEvent.KEYCODE_RIGHT_BRACKET
            KEYCODE_BACKSLASH -> KeyEvent.KEYCODE_BACKSLASH
            KEYCODE_SEMICOLON -> KeyEvent.KEYCODE_SEMICOLON
            KEYCODE_APOSTROPHE -> KeyEvent.KEYCODE_APOSTROPHE
            KEYCODE_SLASH -> KeyEvent.KEYCODE_SLASH
            KEYCODE_AT -> KeyEvent.KEYCODE_AT
            KEYCODE_NUM -> KeyEvent.KEYCODE_NUM
            KEYCODE_HEADSETHOOK -> KeyEvent.KEYCODE_HEADSETHOOK
            KEYCODE_FOCUS -> KeyEvent.KEYCODE_FOCUS
            KEYCODE_PLUS -> KeyEvent.KEYCODE_PLUS
            KEYCODE_MENU -> KeyEvent.KEYCODE_MENU
            KEYCODE_NOTIFICATION -> KeyEvent.KEYCODE_NOTIFICATION
            KEYCODE_SEARCH -> KeyEvent.KEYCODE_SEARCH
            KEYCODE_MEDIA_PLAY_PAUSE -> KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE
            KEYCODE_MEDIA_STOP -> KeyEvent.KEYCODE_MEDIA_STOP
            KEYCODE_MEDIA_NEXT -> KeyEvent.KEYCODE_MEDIA_NEXT
            KEYCODE_MEDIA_PREVIOUS -> KeyEvent.KEYCODE_MEDIA_PREVIOUS
            KEYCODE_MEDIA_REWIND -> KeyEvent.KEYCODE_MEDIA_REWIND
            KEYCODE_MEDIA_FAST_FORWARD -> KeyEvent.KEYCODE_MEDIA_FAST_FORWARD
            KEYCODE_MUTE -> KeyEvent.KEYCODE_MUTE
            KEYCODE_PAGE_UP -> KeyEvent.KEYCODE_PAGE_UP
            KEYCODE_PAGE_DOWN -> KeyEvent.KEYCODE_PAGE_DOWN
            KEYCODE_PICTSYMBOLS -> KeyEvent.KEYCODE_PICTSYMBOLS
            KEYCODE_SWITCH_CHARSET -> KeyEvent.KEYCODE_SWITCH_CHARSET
            KEYCODE_BUTTON_A -> KeyEvent.KEYCODE_BUTTON_A
            KEYCODE_BUTTON_B -> KeyEvent.KEYCODE_BUTTON_B
            KEYCODE_BUTTON_C -> KeyEvent.KEYCODE_BUTTON_C
            KEYCODE_BUTTON_X -> KeyEvent.KEYCODE_BUTTON_X
            KEYCODE_BUTTON_Y -> KeyEvent.KEYCODE_BUTTON_Y
            KEYCODE_BUTTON_Z -> KeyEvent.KEYCODE_BUTTON_Z
            KEYCODE_BUTTON_L1 -> KeyEvent.KEYCODE_BUTTON_L1
            KEYCODE_BUTTON_R1 -> KeyEvent.KEYCODE_BUTTON_R1
            KEYCODE_BUTTON_L2 -> KeyEvent.KEYCODE_BUTTON_L2
            KEYCODE_BUTTON_R2 -> KeyEvent.KEYCODE_BUTTON_R2
            KEYCODE_BUTTON_THUMBL -> KeyEvent.KEYCODE_BUTTON_THUMBL
            KEYCODE_BUTTON_THUMBR -> KeyEvent.KEYCODE_BUTTON_THUMBR
            KEYCODE_BUTTON_START -> KeyEvent.KEYCODE_BUTTON_START
            KEYCODE_BUTTON_SELECT -> KeyEvent.KEYCODE_BUTTON_SELECT
            KEYCODE_BUTTON_MODE -> KeyEvent.KEYCODE_BUTTON_MODE
            KEYCODE_ESCAPE -> KeyEvent.KEYCODE_ESCAPE
            KEYCODE_FORWARD_DEL -> KeyEvent.KEYCODE_FORWARD_DEL
            KEYCODE_CTRL_LEFT -> KeyEvent.KEYCODE_CTRL_LEFT
            KEYCODE_CTRL_RIGHT -> KeyEvent.KEYCODE_CTRL_RIGHT
            KEYCODE_CAPS_LOCK -> KeyEvent.KEYCODE_CAPS_LOCK
            KEYCODE_SCROLL_LOCK -> KeyEvent.KEYCODE_SCROLL_LOCK
            KEYCODE_META_LEFT -> KeyEvent.KEYCODE_META_LEFT
            KEYCODE_META_RIGHT -> KeyEvent.KEYCODE_META_RIGHT
            KEYCODE_FUNCTION -> KeyEvent.KEYCODE_FUNCTION
            KEYCODE_SYSRQ -> KeyEvent.KEYCODE_SYSRQ
            KEYCODE_BREAK -> KeyEvent.KEYCODE_BREAK
            KEYCODE_MOVE_HOME -> KeyEvent.KEYCODE_MOVE_HOME
            KEYCODE_MOVE_END -> KeyEvent.KEYCODE_MOVE_END
            KEYCODE_INSERT -> KeyEvent.KEYCODE_INSERT
            KEYCODE_FORWARD -> KeyEvent.KEYCODE_FORWARD
            KEYCODE_MEDIA_PLAY -> KeyEvent.KEYCODE_MEDIA_PLAY
            KEYCODE_MEDIA_PAUSE -> KeyEvent.KEYCODE_MEDIA_PAUSE
            KEYCODE_MEDIA_CLOSE -> KeyEvent.KEYCODE_MEDIA_CLOSE
            KEYCODE_MEDIA_EJECT -> KeyEvent.KEYCODE_MEDIA_EJECT
            KEYCODE_MEDIA_RECORD -> KeyEvent.KEYCODE_MEDIA_RECORD
            KEYCODE_F1 -> KeyEvent.KEYCODE_F1
            KEYCODE_F2 -> KeyEvent.KEYCODE_F2
            KEYCODE_F3 -> KeyEvent.KEYCODE_F3
            KEYCODE_F4 -> KeyEvent.KEYCODE_F4
            KEYCODE_F5 -> KeyEvent.KEYCODE_F5
            KEYCODE_F6 -> KeyEvent.KEYCODE_F6
            KEYCODE_F7 -> KeyEvent.KEYCODE_F7
            KEYCODE_F8 -> KeyEvent.KEYCODE_F8
            KEYCODE_F9 -> KeyEvent.KEYCODE_F9
            KEYCODE_F10 -> KeyEvent.KEYCODE_F10
            KEYCODE_F11 -> KeyEvent.KEYCODE_F11
            KEYCODE_F12 -> KeyEvent.KEYCODE_F12
            KEYCODE_NUM_LOCK -> KeyEvent.KEYCODE_NUM_LOCK
            KEYCODE_NUMPAD_0 -> KeyEvent.KEYCODE_NUMPAD_0
            KEYCODE_NUMPAD_1 -> KeyEvent.KEYCODE_NUMPAD_1
            KEYCODE_NUMPAD_2 -> KeyEvent.KEYCODE_NUMPAD_2
            KEYCODE_NUMPAD_3 -> KeyEvent.KEYCODE_NUMPAD_3
            KEYCODE_NUMPAD_4 -> KeyEvent.KEYCODE_NUMPAD_4
            KEYCODE_NUMPAD_5 -> KeyEvent.KEYCODE_NUMPAD_5
            KEYCODE_NUMPAD_6 -> KeyEvent.KEYCODE_NUMPAD_6
            KEYCODE_NUMPAD_7 -> KeyEvent.KEYCODE_NUMPAD_7
            KEYCODE_NUMPAD_8 -> KeyEvent.KEYCODE_NUMPAD_8
            KEYCODE_NUMPAD_9 -> KeyEvent.KEYCODE_NUMPAD_9
            KEYCODE_NUMPAD_DIVIDE -> KeyEvent.KEYCODE_NUMPAD_DIVIDE
            KEYCODE_NUMPAD_MULTIPLY -> KeyEvent.KEYCODE_NUMPAD_MULTIPLY
            KEYCODE_NUMPAD_SUBTRACT -> KeyEvent.KEYCODE_NUMPAD_SUBTRACT
            KEYCODE_NUMPAD_ADD -> KeyEvent.KEYCODE_NUMPAD_ADD
            KEYCODE_NUMPAD_DOT -> KeyEvent.KEYCODE_NUMPAD_DOT
            KEYCODE_NUMPAD_COMMA -> KeyEvent.KEYCODE_NUMPAD_COMMA
            KEYCODE_NUMPAD_ENTER -> KeyEvent.KEYCODE_NUMPAD_ENTER
            KEYCODE_NUMPAD_EQUALS -> KeyEvent.KEYCODE_NUMPAD_EQUALS
            KEYCODE_NUMPAD_LEFT_PAREN -> KeyEvent.KEYCODE_NUMPAD_LEFT_PAREN
            KEYCODE_NUMPAD_RIGHT_PAREN -> KeyEvent.KEYCODE_NUMPAD_RIGHT_PAREN
            KEYCODE_VOLUME_MUTE -> KeyEvent.KEYCODE_VOLUME_MUTE
            KEYCODE_INFO -> KeyEvent.KEYCODE_INFO
            KEYCODE_CHANNEL_UP -> KeyEvent.KEYCODE_CHANNEL_UP
            KEYCODE_CHANNEL_DOWN -> KeyEvent.KEYCODE_CHANNEL_DOWN
            KEYCODE_ZOOM_IN -> KeyEvent.KEYCODE_ZOOM_IN
            KEYCODE_ZOOM_OUT -> KeyEvent.KEYCODE_ZOOM_OUT
            KEYCODE_TV -> KeyEvent.KEYCODE_TV
            KEYCODE_WINDOW -> KeyEvent.KEYCODE_WINDOW
            KEYCODE_GUIDE -> KeyEvent.KEYCODE_GUIDE
            KEYCODE_DVR -> KeyEvent.KEYCODE_DVR
            KEYCODE_BOOKMARK -> KeyEvent.KEYCODE_BOOKMARK
            KEYCODE_CAPTIONS -> KeyEvent.KEYCODE_CAPTIONS
            KEYCODE_SETTINGS -> KeyEvent.KEYCODE_SETTINGS
            KEYCODE_TV_POWER -> KeyEvent.KEYCODE_TV_POWER
            KEYCODE_TV_INPUT -> KeyEvent.KEYCODE_TV_INPUT
            KEYCODE_STB_POWER -> KeyEvent.KEYCODE_STB_POWER
            KEYCODE_STB_INPUT -> KeyEvent.KEYCODE_STB_INPUT
            KEYCODE_AVR_POWER -> KeyEvent.KEYCODE_AVR_POWER
            KEYCODE_AVR_INPUT -> KeyEvent.KEYCODE_AVR_INPUT
            KEYCODE_PROG_RED -> KeyEvent.KEYCODE_PROG_RED
            KEYCODE_PROG_GREEN -> KeyEvent.KEYCODE_PROG_GREEN
            KEYCODE_PROG_YELLOW -> KeyEvent.KEYCODE_PROG_YELLOW
            KEYCODE_PROG_BLUE -> KeyEvent.KEYCODE_PROG_BLUE
            KEYCODE_APP_SWITCH -> KeyEvent.KEYCODE_APP_SWITCH
            KEYCODE_BUTTON_1 -> KeyEvent.KEYCODE_BUTTON_1
            KEYCODE_BUTTON_2 -> KeyEvent.KEYCODE_BUTTON_2
            KEYCODE_BUTTON_3 -> KeyEvent.KEYCODE_BUTTON_3
            KEYCODE_BUTTON_4 -> KeyEvent.KEYCODE_BUTTON_4
            KEYCODE_BUTTON_5 -> KeyEvent.KEYCODE_BUTTON_5
            KEYCODE_BUTTON_6 -> KeyEvent.KEYCODE_BUTTON_6
            KEYCODE_BUTTON_7 -> KeyEvent.KEYCODE_BUTTON_7
            KEYCODE_BUTTON_8 -> KeyEvent.KEYCODE_BUTTON_8
            KEYCODE_BUTTON_9 -> KeyEvent.KEYCODE_BUTTON_9
            KEYCODE_BUTTON_10 -> KeyEvent.KEYCODE_BUTTON_10
            KEYCODE_BUTTON_11 -> KeyEvent.KEYCODE_BUTTON_11
            KEYCODE_BUTTON_12 -> KeyEvent.KEYCODE_BUTTON_12
            KEYCODE_BUTTON_13 -> KeyEvent.KEYCODE_BUTTON_13
            KEYCODE_BUTTON_14 -> KeyEvent.KEYCODE_BUTTON_14
            KEYCODE_BUTTON_15 -> KeyEvent.KEYCODE_BUTTON_15
            KEYCODE_BUTTON_16 -> KeyEvent.KEYCODE_BUTTON_16
            KEYCODE_LANGUAGE_SWITCH -> KeyEvent.KEYCODE_LANGUAGE_SWITCH
            KEYCODE_MANNER_MODE -> KeyEvent.KEYCODE_MANNER_MODE
            KEYCODE_3D_MODE -> KeyEvent.KEYCODE_3D_MODE
            KEYCODE_CONTACTS -> KeyEvent.KEYCODE_CONTACTS
            KEYCODE_CALENDAR -> KeyEvent.KEYCODE_CALENDAR
            KEYCODE_MUSIC -> KeyEvent.KEYCODE_MUSIC
            KEYCODE_CALCULATOR -> KeyEvent.KEYCODE_CALCULATOR
            KEYCODE_ZENKAKU_HANKAKU -> KeyEvent.KEYCODE_ZENKAKU_HANKAKU
            KEYCODE_EISU -> KeyEvent.KEYCODE_EISU
            KEYCODE_MUHENKAN -> KeyEvent.KEYCODE_MUHENKAN
            KEYCODE_HENKAN -> KeyEvent.KEYCODE_HENKAN
            KEYCODE_KATAKANA_HIRAGANA -> KeyEvent.KEYCODE_KATAKANA_HIRAGANA
            KEYCODE_YEN -> KeyEvent.KEYCODE_YEN
            KEYCODE_RO -> KeyEvent.KEYCODE_RO
            KEYCODE_KANA -> KeyEvent.KEYCODE_KANA
            KEYCODE_ASSIST -> KeyEvent.KEYCODE_ASSIST
            KEYCODE_BRIGHTNESS_DOWN -> KeyEvent.KEYCODE_BRIGHTNESS_DOWN
            KEYCODE_BRIGHTNESS_UP -> KeyEvent.KEYCODE_BRIGHTNESS_UP
            KEYCODE_MEDIA_AUDIO_TRACK -> KeyEvent.KEYCODE_MEDIA_AUDIO_TRACK
            KEYCODE_SLEEP -> KeyEvent.KEYCODE_SLEEP
            KEYCODE_WAKEUP -> KeyEvent.KEYCODE_WAKEUP
            KEYCODE_PAIRING -> KeyEvent.KEYCODE_PAIRING
            KEYCODE_MEDIA_TOP_MENU -> KeyEvent.KEYCODE_MEDIA_TOP_MENU
            KEYCODE_11 -> KeyEvent.KEYCODE_11
            KEYCODE_12 -> KeyEvent.KEYCODE_12
            KEYCODE_LAST_CHANNEL -> KeyEvent.KEYCODE_LAST_CHANNEL
            KEYCODE_TV_DATA_SERVICE -> KeyEvent.KEYCODE_TV_DATA_SERVICE
            KEYCODE_VOICE_ASSIST -> KeyEvent.KEYCODE_VOICE_ASSIST
            KEYCODE_TV_RADIO_SERVICE -> KeyEvent.KEYCODE_TV_RADIO_SERVICE
            KEYCODE_TV_TELETEXT -> KeyEvent.KEYCODE_TV_TELETEXT
            KEYCODE_TV_NUMBER_ENTRY -> KeyEvent.KEYCODE_TV_NUMBER_ENTRY
            KEYCODE_TV_TERRESTRIAL_ANALOG -> KeyEvent.KEYCODE_TV_TERRESTRIAL_ANALOG
            KEYCODE_TV_TERRESTRIAL_DIGITAL -> KeyEvent.KEYCODE_TV_TERRESTRIAL_DIGITAL
            KEYCODE_TV_SATELLITE -> KeyEvent.KEYCODE_TV_SATELLITE
            KEYCODE_TV_SATELLITE_BS -> KeyEvent.KEYCODE_TV_SATELLITE_BS
            KEYCODE_TV_SATELLITE_CS -> KeyEvent.KEYCODE_TV_SATELLITE_CS
            KEYCODE_TV_SATELLITE_SERVICE -> KeyEvent.KEYCODE_TV_SATELLITE_SERVICE
            KEYCODE_TV_NETWORK -> KeyEvent.KEYCODE_TV_NETWORK
            KEYCODE_TV_ANTENNA_CABLE -> KeyEvent.KEYCODE_TV_ANTENNA_CABLE
            KEYCODE_TV_INPUT_HDMI_1 -> KeyEvent.KEYCODE_TV_INPUT_HDMI_1
            KEYCODE_TV_INPUT_HDMI_2 -> KeyEvent.KEYCODE_TV_INPUT_HDMI_2
            KEYCODE_TV_INPUT_HDMI_3 -> KeyEvent.KEYCODE_TV_INPUT_HDMI_3
            KEYCODE_TV_INPUT_HDMI_4 -> KeyEvent.KEYCODE_TV_INPUT_HDMI_4
            KEYCODE_TV_INPUT_COMPOSITE_1 -> KeyEvent.KEYCODE_TV_INPUT_COMPOSITE_1
            KEYCODE_TV_INPUT_COMPOSITE_2 -> KeyEvent.KEYCODE_TV_INPUT_COMPOSITE_2
            KEYCODE_TV_INPUT_COMPONENT_1 -> KeyEvent.KEYCODE_TV_INPUT_COMPONENT_1
            KEYCODE_TV_INPUT_COMPONENT_2 -> KeyEvent.KEYCODE_TV_INPUT_COMPONENT_2
            KEYCODE_TV_INPUT_VGA_1 -> KeyEvent.KEYCODE_TV_INPUT_VGA_1
            KEYCODE_TV_AUDIO_DESCRIPTION -> KeyEvent.KEYCODE_TV_AUDIO_DESCRIPTION
            KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP -> KeyEvent.KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP
            KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN -> KeyEvent.KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN
            KEYCODE_TV_ZOOM_MODE -> KeyEvent.KEYCODE_TV_ZOOM_MODE
            KEYCODE_TV_CONTENTS_MENU -> KeyEvent.KEYCODE_TV_CONTENTS_MENU
            KEYCODE_TV_MEDIA_CONTEXT_MENU -> KeyEvent.KEYCODE_TV_MEDIA_CONTEXT_MENU
            KEYCODE_TV_TIMER_PROGRAMMING -> KeyEvent.KEYCODE_TV_TIMER_PROGRAMMING
            KEYCODE_HELP -> KeyEvent.KEYCODE_HELP
            KEYCODE_NAVIGATE_PREVIOUS -> KeyEvent.KEYCODE_NAVIGATE_PREVIOUS
            KEYCODE_NAVIGATE_NEXT -> KeyEvent.KEYCODE_NAVIGATE_NEXT
            KEYCODE_NAVIGATE_IN -> KeyEvent.KEYCODE_NAVIGATE_IN
            KEYCODE_NAVIGATE_OUT -> KeyEvent.KEYCODE_NAVIGATE_OUT
            KEYCODE_STEM_PRIMARY -> KeyEvent.KEYCODE_STEM_PRIMARY
            KEYCODE_STEM_1 -> KeyEvent.KEYCODE_STEM_1
            KEYCODE_STEM_2 -> KeyEvent.KEYCODE_STEM_2
            KEYCODE_STEM_3 -> KeyEvent.KEYCODE_STEM_3
            KEYCODE_DPAD_UP_LEFT -> KeyEvent.KEYCODE_DPAD_UP_LEFT
            KEYCODE_DPAD_DOWN_LEFT -> KeyEvent.KEYCODE_DPAD_DOWN_LEFT
            KEYCODE_DPAD_UP_RIGHT -> KeyEvent.KEYCODE_DPAD_UP_RIGHT
            KEYCODE_DPAD_DOWN_RIGHT -> KeyEvent.KEYCODE_DPAD_DOWN_RIGHT
            KEYCODE_MEDIA_SKIP_FORWARD -> KeyEvent.KEYCODE_MEDIA_SKIP_FORWARD
            KEYCODE_MEDIA_SKIP_BACKWARD -> KeyEvent.KEYCODE_MEDIA_SKIP_BACKWARD
            KEYCODE_MEDIA_STEP_FORWARD -> KeyEvent.KEYCODE_MEDIA_STEP_FORWARD
            KEYCODE_MEDIA_STEP_BACKWARD -> KeyEvent.KEYCODE_MEDIA_STEP_BACKWARD
            KEYCODE_SOFT_SLEEP -> KeyEvent.KEYCODE_SOFT_SLEEP
            KEYCODE_CUT -> KeyEvent.KEYCODE_CUT
            KEYCODE_COPY -> KeyEvent.KEYCODE_COPY
            KEYCODE_PASTE -> KeyEvent.KEYCODE_PASTE
            KEYCODE_SYSTEM_NAVIGATION_UP -> KeyEvent.KEYCODE_SYSTEM_NAVIGATION_UP
            KEYCODE_SYSTEM_NAVIGATION_DOWN -> KeyEvent.KEYCODE_SYSTEM_NAVIGATION_DOWN
            KEYCODE_SYSTEM_NAVIGATION_LEFT -> KeyEvent.KEYCODE_SYSTEM_NAVIGATION_LEFT
            KEYCODE_SYSTEM_NAVIGATION_RIGHT -> KeyEvent.KEYCODE_SYSTEM_NAVIGATION_RIGHT
            KEYCODE_ALL_APPS -> KeyEvent.KEYCODE_ALL_APPS
            KEYCODE_REFRESH -> KeyEvent.KEYCODE_REFRESH
            KEYCODE_THUMBS_UP -> KeyEvent.KEYCODE_THUMBS_UP
            KEYCODE_THUMBS_DOWN -> KeyEvent.KEYCODE_THUMBS_DOWN
            KEYCODE_PROFILE_SWITCH -> KeyEvent.KEYCODE_PROFILE_SWITCH
        }
}
