name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-win:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        run: cd client && rustup component add clippy
      - name: Build
        run: cd client && cargo build --release
      - name: Clippy
        run: cd client && cargo -v clippy
      - uses: actions/upload-artifact@v2
        with:
          name: android-commander-win
          path: client/target/release/android-commander.exe
          if-no-files-found: error
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        run: cd client && rustup component add clippy
      - name: Build
        run: cd client && cargo build --release
      - name: Clippy
        run: cd client && cargo -v clippy
      - uses: actions/upload-artifact@v2
        with:
          name: android-commander-linux
          path: client/target/release/android-commander
          if-no-files-found: error
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        run: cd client && rustup component add rustfmt
      - run: cd client && cargo -v fmt -- --check
