name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-android-commander-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make -C server
      - uses: actions/upload-artifact@v2
        with:
          name: android-commander-server
          path: server/app/build/outputs/android-commander-server
          if-no-files-found: error
  build-win:
    needs:
      - build-android-commander-server
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: android-commander-server
          path: server/app/build/outputs/android-commander-server
      - name: Setup Rust
        run: make -C client prepare
      - name: Build
        run: make -C client
      - name: Clippy
        run: make -C client lint
      - uses: actions/upload-artifact@v2
        with:
          name: android-commander-win
          path: client/target/release/android-commander.exe
          if-no-files-found: error
  build-ubuntu:
    needs:
      - build-android-commander-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: android-commander-server
          path: server/app/build/outputs/android-commander-server
      - name: Setup Rust
        run: make -C client prepare
      - name: Build
        run: make -C client
      - name: Clippy
        run: make -C client lint
      - uses: actions/upload-artifact@v2
        with:
          name: android-commander-linux
          path: client/target/release/android-commander
          if-no-files-found: error
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make -C client prepare fmt
